# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 487)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 380, 480))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.614, y1:0.607955, x2:0.994318, y2:0, stop:0 rgba(164, 164, 246, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 9px;")
        self.widget.setObjectName("widget")
        self.tb3 = QtWidgets.QLineEdit(self.widget)
        self.tb3.setGeometry(QtCore.QRect(70, 150, 251, 40))
        self.tb3.setStyleSheet("background-color: rgba(47,42,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius: 9px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb3.setObjectName("tb3")
        self.tb4 = QtWidgets.QLineEdit(self.widget)
        self.tb4.setGeometry(QtCore.QRect(70, 210, 251, 40))
        self.tb4.setStyleSheet("background-color: rgba(47,42,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius: 9px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tb4.setObjectName("tb4")
        self.b3 = QtWidgets.QPushButton(self.widget)
        self.b3.setGeometry(QtCore.QRect(150, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.b3.setFont(font)
        self.b3.setStyleSheet("QPushButton#b3{\n"
"background-color:rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 13px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b3: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b3.setObjectName("b3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 101, 91))
        self.label_3.setStyleSheet("background-color:url(:/Prefix2/user1.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("user1.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.tb5 = QtWidgets.QLineEdit(self.widget)
        self.tb5.setGeometry(QtCore.QRect(70, 270, 251, 40))
        self.tb5.setStyleSheet("background-color: rgba(47,42,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius: 9px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb5.setObjectName("tb5")
        self.b4 = QtWidgets.QPushButton(self.widget)
        self.b4.setGeometry(QtCore.QRect(150, 430, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.b4.setFont(font)
        self.b4.setStyleSheet("QPushButton#b4{\n"
"background-color:rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 13px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b4: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b4.setObjectName("b4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 370, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("text-align:center;\n"
"font-size:10px;\n"
"color: rgb(85, 0, 255);\n"
"background: rgb(166, 166, 249);\n"
"border-radius:2px;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(160, 400, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align:center;\n"
"font-size:10px;\n"
"color: rgb(85, 0, 255);\n"
"background: rgb(166, 166, 249);\n"
"border-radius:2px;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tb3.setPlaceholderText(_translate("Form", "Enter the username here........."))
        self.tb4.setPlaceholderText(_translate("Form", "Enter the password  here........."))
        self.b3.setText(_translate("Form", "Sign Up"))
        self.tb5.setPlaceholderText(_translate("Form", "Enter our Email ID here........."))
        self.b4.setText(_translate("Form", "Log In"))
        self.label_2.setText(_translate("Form", "Registered User"))
        self.label_4.setText(_translate("Form", "Login Here"))
import test1_rc
import test_rc
