# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 487)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 380, 480))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.614, y1:0.607955, x2:0.994318, y2:0, stop:0 rgba(164, 164, 246, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 9px;")
        self.widget.setObjectName("widget")
        self.tb1 = QtWidgets.QLineEdit(self.widget)
        self.tb1.setGeometry(QtCore.QRect(80, 150, 211, 40))
        self.tb1.setStyleSheet("background-color: rgba(47,42,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius: 9px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb1.setObjectName("tb1")
        self.tb2 = QtWidgets.QLineEdit(self.widget)
        self.tb2.setGeometry(QtCore.QRect(80, 220, 211, 40))
        self.tb2.setStyleSheet("background-color: rgba(47,42,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius: 9px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tb2.setObjectName("tb2")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(150, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.b1.setFont(font)
        self.b1.setStyleSheet("QPushButton#b1{\n"
"background-color:rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 13px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b1: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b1.setObjectName("b1")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 20, 121, 101))
        self.label.setStyleSheet("background-color:url(:/Prefix1/logo_200x200.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo_200x200.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.b2 = QtWidgets.QPushButton(self.widget)
        self.b2.setGeometry(QtCore.QRect(150, 400, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.b2.setFont(font)
        self.b2.setStyleSheet("QPushButton#b2{\n"
"background-color:rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 13px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b2: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b2.setObjectName("b2")
        self.l1 = QtWidgets.QLabel(self.widget)
        self.l1.setGeometry(QtCore.QRect(170, 340, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.l1.setFont(font)
        self.l1.setStyleSheet("text-align:center;\n"
"font-size:10px;\n"
"color: rgb(85, 0, 255);\n"
"background: rgb(166, 166, 249);\n"
"border-radius:2px;")
        self.l1.setText("New User")
        self.l1.setObjectName("l1")
        self.l2_2 = QtWidgets.QLabel(self.widget)
        self.l2_2.setGeometry(QtCore.QRect(160, 370, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.l2_2.setFont(font)
        self.l2_2.setStyleSheet("text-align:center;\n"
"font-size:10px;\n"
"color: rgb(85, 0, 255);\n"
"background: rgb(166, 166, 249);\n"
"border-radius:2px;")
        self.l2_2.setObjectName("l2_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tb1.setPlaceholderText(_translate("Form", "Enter the username here........."))
        self.tb2.setPlaceholderText(_translate("Form", "Enter the password  here........."))
        self.b1.setText(_translate("Form", "Login"))
        self.b2.setText(_translate("Form", "Sign Up"))
        self.l2_2.setText(_translate("Form", "Sign up Here"))
import logo1_rc
import test_rc
