# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.widget.setStyleSheet("background-color:rgb(235, 226, 244);\n"
"border-radius: 9px;")
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(260, 260, 500, 320))
        self.groupBox.setStyleSheet("background-color:rgba(192, 192, 192, 50);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.b3 = QtWidgets.QPushButton(self.groupBox)
        self.b3.setGeometry(QtCore.QRect(100, 260, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.b3.setFont(font)
        self.b3.setStyleSheet("QPushButton#b3{\n"
"background-color:rgb(124, 0, 186);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 19px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b3: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b3.setObjectName("b3")
        self.tb5 = QtWidgets.QLineEdit(self.groupBox)
        self.tb5.setGeometry(QtCore.QRect(100, 200, 320, 42))
        self.tb5.setStyleSheet("background-color: rgb(177, 178, 181);\n"
"color:rgb(255,255,255);\n"
"padding-left: 10px;\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb5.setAlignment(QtCore.Qt.AlignCenter)
        self.tb5.setObjectName("tb5")
        self.tb6 = QtWidgets.QLineEdit(self.groupBox)
        self.tb6.setGeometry(QtCore.QRect(100, 140, 320, 42))
        self.tb6.setStyleSheet("background-color: rgb(177, 178, 181);\n"
"color:rgb(255,255,255);\n"
"padding-left: 10px;\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tb6.setAlignment(QtCore.Qt.AlignCenter)
        self.tb6.setObjectName("tb6")
        self.tb3 = QtWidgets.QLineEdit(self.groupBox)
        self.tb3.setGeometry(QtCore.QRect(100, 30, 320, 42))
        self.tb3.setStyleSheet("background-color: rgb(177, 178, 181);\n"
"color:rgb(255,255,255);\n"
"padding-left: 10px;\n"
"border-bottom-color: rgba(46,82,101,255);")
        self.tb3.setAlignment(QtCore.Qt.AlignCenter)
        self.tb3.setObjectName("tb3")
        self.tb4 = QtWidgets.QLineEdit(self.groupBox)
        self.tb4.setGeometry(QtCore.QRect(100, 80, 320, 42))
        self.tb4.setStyleSheet("background-color: rgb(177, 178, 181);\n"
"color:rgb(255,255,255);\n"
"padding-left: 10px;\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"")
        self.tb4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tb4.setAlignment(QtCore.Qt.AlignCenter)
        self.tb4.setObjectName("tb4")
        self.l8 = QtWidgets.QLabel(self.widget)
        self.l8.setGeometry(QtCore.QRect(390, 610, 261, 20))
        self.l8.setStyleSheet("text-align:center;\n"
"font-size:20px;\n"
"color: rgb(0,0,0);\n"
"border-radius:2px;")
        self.l8.setObjectName("l8")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(420, 30, 191, 191))
        self.label.setStyleSheet("background-image:url(logo_200x200.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.b4 = QtWidgets.QPushButton(self.widget)
        self.b4.setGeometry(QtCore.QRect(360, 650, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.b4.setFont(font)
        self.b4.setStyleSheet("QPushButton#b4{\n"
"background-color:rgb(124, 0, 186);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 19px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#b4: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.b4.setObjectName("b4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b3.setText(_translate("Form", "Submit"))
        self.tb5.setPlaceholderText(_translate("Form", "Enter email here.........       "))
        self.tb6.setPlaceholderText(_translate("Form", "Repeat password .........   "))
        self.tb3.setPlaceholderText(_translate("Form", "Enter username here........."))
        self.tb4.setPlaceholderText(_translate("Form", "Enter password  here........."))
        self.l8.setText(_translate("Form", "Already have an account?"))
        self.b4.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
