# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercises.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1175, 768)
        Form.setStyleSheet("background-color:rgb(235, 226, 244);\n"
"border-radius: 9px;")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(200, 320, 625, 300))
        self.groupBox.setStyleSheet("background-color:rgba(255, 136, 4, 0.2);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.next_btn = QtWidgets.QPushButton(self.groupBox)
        self.next_btn.setGeometry(QtCore.QRect(220, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("QPushButton#next_btn{\n"
"background-color:rgb(255, 136, 4);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#next_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.next_btn.setObjectName("next_btn")
        self.back_btn = QtWidgets.QPushButton(self.groupBox)
        self.back_btn.setGeometry(QtCore.QRect(30, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton#back_btn{\n"
"background-color:rgb(255, 136, 4);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#back_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.back_btn.setObjectName("back_btn")
        self.main_btn = QtWidgets.QPushButton(self.groupBox)
        self.main_btn.setGeometry(QtCore.QRect(410, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.main_btn.setFont(font)
        self.main_btn.setStyleSheet("QPushButton#main_btn{\n"
"background-color:rgb(255, 136, 4);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#main_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.main_btn.setObjectName("main_btn")
        self.picture = QtWidgets.QLabel(self.groupBox)
        self.picture.setGeometry(QtCore.QRect(395, 20, 190, 190))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.picture.setFont(font)
        self.picture.setStyleSheet("border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px;\n"
"    \n"
"    border-image: url(static/images/001.jpg) 10 10 10 10 stretch stretch;")
        self.picture.setText("")
        self.picture.setScaledContents(True)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setWordWrap(False)
        self.picture.setIndent(0)
        self.picture.setObjectName("picture")
        self.Exercise = QtWidgets.QLabel(self.groupBox)
        self.Exercise.setGeometry(QtCore.QRect(30, 20, 355, 190))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        font.setBold(False)
        font.setWeight(50)
        self.Exercise.setFont(font)
        self.Exercise.setAutoFillBackground(False)
        self.Exercise.setStyleSheet("    border: 1px ;\n"
"    padding: 15px;\n"
"    border-radius: 10px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"font-size: 16px;\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:400;")
        self.Exercise.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Exercise.setWordWrap(True)
        self.Exercise.setObjectName("Exercise")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(416, 50, 191, 181))
        self.label.setStyleSheet("background-image:url(static/images/logo.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(820, 60, 175, 40))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.logout.setFont(font)
        self.logout.setStyleSheet("QPushButton#logout{\n"
"background-color:rgba(192, 192, 192,200);\n"
"color:rgb(124, 0, 186);\n"
"font-size: 12px;\n"
"border-radius : 7px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"\n"
"\n"
"}\n"
"QPushButton#logout: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.logout.setObjectName("logout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_btn.setText(_translate("Form", "Next"))
        self.back_btn.setText(_translate("Form", "Back"))
        self.main_btn.setText(_translate("Form", "Main Menu"))
        self.Exercise.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#644f82;\">Exercise 1:</span></p><p><span style=\" font-size:12pt; color:#644f82;\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s,</span></p></body></html>"))
        self.logout.setText(_translate("Form", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
