# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        Form.setStyleSheet("background-color:rgb(235, 226, 244);\n"
"border-radius: 9px;")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(202, 320, 625, 300))
        self.groupBox.setStyleSheet("background-color:rgba(48, 213, 200, 0.2);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.next_btn = QtWidgets.QPushButton(self.groupBox)
        self.next_btn.setGeometry(QtCore.QRect(226, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("QPushButton#next_btn{\n"
"background-color:rgb(48, 213, 200);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#next_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.next_btn.setObjectName("next_btn")
        self.back_btn = QtWidgets.QPushButton(self.groupBox)
        self.back_btn.setGeometry(QtCore.QRect(36, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton#back_btn{\n"
"background-color:rgb(48, 213, 200);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#back_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.back_btn.setObjectName("back_btn")
        self.main_btn = QtWidgets.QPushButton(self.groupBox)
        self.main_btn.setGeometry(QtCore.QRect(416, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.main_btn.setFont(font)
        self.main_btn.setStyleSheet("QPushButton#main_btn{\n"
"background-color:rgb(48, 213, 200);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#main_btn: pressed {\n"
"background-color:rgb(255, 136, 4);\n"
"}")
        self.main_btn.setObjectName("main_btn")
        self.picture = QtWidgets.QLabel(self.groupBox)
        self.picture.setGeometry(QtCore.QRect(416, 20, 175, 190))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.picture.setFont(font)
        self.picture.setStyleSheet("border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px;\n"
"    \n"
"    border-image: url(static/images/000.jpg) 10 10 10 10 stretch stretch;")
        self.picture.setText("")
        self.picture.setScaledContents(True)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setWordWrap(False)
        self.picture.setIndent(0)
        self.picture.setObjectName("picture")
        self.mute = QtWidgets.QPushButton(self.groupBox)
        self.mute.setGeometry(QtCore.QRect(36, 170, 115, 40))
        self.mute.setStyleSheet("QPushButton#mute{\n"
"background-color: rgba(35, 157, 147, 0.5);\n"
"color: white;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton#mute: pressed{\n"
"background-color: rgba(25, 157, 147, 0.1);\n"
"color: white;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.mute.setObjectName("mute")
        self.play_btn = QtWidgets.QPushButton(self.groupBox)
        self.play_btn.setGeometry(QtCore.QRect(161, 170, 115, 40))
        self.play_btn.setStyleSheet("background-color: rgba(35, 157, 147, 0.5);\n"
"color: white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.play_btn.setObjectName("play_btn")
        self.pause_btn = QtWidgets.QPushButton(self.groupBox)
        self.pause_btn.setGeometry(QtCore.QRect(286, 170, 115, 40))
        self.pause_btn.setStyleSheet("background-color: rgba(35, 157, 147, 0.5);\n"
"color: white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pause_btn.setObjectName("pause_btn")
        self.minus = QtWidgets.QPushButton(self.groupBox)
        self.minus.setGeometry(QtCore.QRect(36, 90, 115, 30))
        self.minus.setStyleSheet("background-color: rgba(35, 157, 147, 0.5);\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.minus.setObjectName("minus")
        self.plus = QtWidgets.QPushButton(self.groupBox)
        self.plus.setGeometry(QtCore.QRect(286, 90, 115, 30))
        self.plus.setStyleSheet("background-color: rgba(35, 157, 147, 0.5);\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.plus.setObjectName("plus")
        self.main_label = QtWidgets.QLabel(self.groupBox)
        self.main_label.setGeometry(QtCore.QRect(40, 30, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.main_label.setFont(font)
        self.main_label.setMouseTracking(False)
        self.main_label.setToolTipDuration(1)
        self.main_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(100, 79, 129);\n"
"font: 18pt \"Arial\";")
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setIndent(1)
        self.main_label.setObjectName("main_label")
        self.volume_label = QtWidgets.QLabel(self.groupBox)
        self.volume_label.setGeometry(QtCore.QRect(160, 80, 111, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.volume_label.setFont(font)
        self.volume_label.setMouseTracking(False)
        self.volume_label.setToolTipDuration(1)
        self.volume_label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(100, 79, 129);\n"
"font: 16pt \"Arial\";")
        self.volume_label.setAlignment(QtCore.Qt.AlignCenter)
        self.volume_label.setIndent(1)
        self.volume_label.setObjectName("volume_label")
        self.now_playing_label = QtWidgets.QLabel(self.groupBox)
        self.now_playing_label.setGeometry(QtCore.QRect(40, 135, 350, 20))
        self.now_playing_label.setText("")
        self.now_playing_label.setAlignment(QtCore.Qt.AlignCenter)
        self.now_playing_label.setObjectName("now_playing_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(416, 50, 191, 181))
        self.label.setStyleSheet("background-image:url(static/images/logo.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(820, 60, 175, 40))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.logout.setFont(font)
        self.logout.setStyleSheet("QPushButton#logout{\n"
"background-color:rgba(192, 192, 192,200);\n"
"color:rgb(124, 0, 186);\n"
"font-size: 12px;\n"
"border-radius : 7px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"\n"
"\n"
"}\n"
"QPushButton#logout: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.logout.setObjectName("logout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_btn.setText(_translate("Form", "Next"))
        self.back_btn.setText(_translate("Form", "Back"))
        self.main_btn.setText(_translate("Form", "Main Menu"))
        self.mute.setText(_translate("Form", "mute"))
        self.play_btn.setText(_translate("Form", "play"))
        self.pause_btn.setText(_translate("Form", "pause"))
        self.minus.setText(_translate("Form", "-"))
        self.plus.setText(_translate("Form", "+"))
        self.main_label.setText(_translate("Form", "Relaxing Music"))
        self.volume_label.setText(_translate("Form", "Volume"))
        self.logout.setText(_translate("Form", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
