# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personality.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonalityTest(object):
    ''' This class provides information about a personality'''
    def setupUi(self, PersonalityTest):
        PersonalityTest.setObjectName("PersonalityTest")
        PersonalityTest.resize(1024, 768)
        PersonalityTest.setStyleSheet("background-color:rgb(235, 226, 244);\n"
"border-radius: 9px;")
        self.logout = QtWidgets.QPushButton(PersonalityTest)
        self.logout.setGeometry(QtCore.QRect(800, 50, 175, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.logout.setFont(font)
        self.logout.setStyleSheet("QPushButton#logout{\n"
"background-color:rgb(192, 192, 192,200);\n"
"color:rgb(124, 0, 186);\n"
"font-size: 12px;\n"
"border-radius : 7px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"\n"
"\n"
"}\n"
)
        self.logout.setObjectName("logout")
        self.groupBox = QtWidgets.QGroupBox(PersonalityTest)
        self.groupBox.setGeometry(QtCore.QRect(190, 350, 625, 300))
        self.groupBox.setStyleSheet("background-color:rgb(192, 192, 192,150);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.next_btn = QtWidgets.QPushButton(self.groupBox)
        self.next_btn.setGeometry(QtCore.QRect(220, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(-1)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("QPushButton#next_btn{\n"
"background-color:rgb(131, 53, 151);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
)
        self.next_btn.setObjectName("next_btn")
        self.back_btn = QtWidgets.QPushButton(self.groupBox)
        self.back_btn.setGeometry(QtCore.QRect(20, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(-1)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton#back_btn{\n"
"background-color:rgb(131, 53, 151);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
)
        self.back_btn.setObjectName("back_btn")
        self.main_btn = QtWidgets.QPushButton(self.groupBox)
        self.main_btn.setGeometry(QtCore.QRect(420, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(-1)
        self.main_btn.setFont(font)
        self.main_btn.setStyleSheet("QPushButton#main_btn{\n"
"background-color:rgb(131, 53, 151);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
)
        self.main_btn.setObjectName("main_btn")
        self.Question_No = QtWidgets.QLineEdit(self.groupBox)
        self.Question_No.setGeometry(QtCore.QRect(80, 30, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(25)
        self.Question_No.setFont(font)
        self.Question_No.setStyleSheet("background-color:rgb(192, 192, 192,0);\n"
"\n"
"color: rgb(100, 79, 130);\n"
"font-size: 26px;\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:200;")
        self.Question_No.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Question_No.setPlaceholderText("")
        self.Question_No.setObjectName("Question_No")
        self.Question_area = QtWidgets.QLineEdit(self.groupBox)
        self.Question_area.setGeometry(QtCore.QRect(90, 100, 521, 20))
        self.Question_area.setStyleSheet("background-color:rgb(192, 192, 192,0);\n"
"\n"
"color: rgb(100, 79, 130);\n"
"font-size: 16px;\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:400;")
        self.Question_area.setObjectName("Question_area")
        self.radioButton1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton1.setGeometry(QtCore.QRect(90, 140, 451, 16))
        self.radioButton1.setStyleSheet("background-color:rgb(192, 192, 192,0);\n"
"font-size: 12px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:200;")
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton2.setGeometry(QtCore.QRect(90, 170, 451, 16))
        self.radioButton2.setStyleSheet("background-color:rgb(192, 192, 192,0);\n"
"font-size: 12px;\n"
"font-family: Sura;\n"
"color: rgb(100, 79, 130);\n"
"\n"
"border-radius : 7px;\n"
"font-weight:200;")
        self.radioButton2.setObjectName("radioButton2")
        self.label = QtWidgets.QLabel(PersonalityTest)
        self.label.setGeometry(QtCore.QRect(420, 100, 191, 181))
        self.label.setStyleSheet("background-image:url(logo_200x200.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(PersonalityTest)
        QtCore.QMetaObject.connectSlotsByName(PersonalityTest)

    def retranslateUi(self, PersonalityTest):
        ''' Initialize the personality'''
        _translate = QtCore.QCoreApplication.translate
        PersonalityTest.setWindowTitle(_translate("PersonalityTest", "Form"))
        self.logout.setText(_translate("PersonalityTest", "Logout"))
        self.next_btn.setText(_translate("PersonalityTest", "Next"))
        self.back_btn.setText(_translate("PersonalityTest", "Back"))
        self.main_btn.setText(_translate("PersonalityTest", "Main Menu"))
        self.Question_No.setText(_translate("PersonalityTest", "Question 1"))
        self.Question_area.setText(_translate("PersonalityTest", "You feel more energetic when:"))
        self.radioButton1.setText(_translate("PersonalityTest", "Socializing with others"))
        self.radioButton2.setText(_translate("PersonalityTest", "Spending time alone"))

