# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quotes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        Form.setStyleSheet("background-color:rgb(235, 226, 244);\n"
"border-radius: 9px;")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(200, 320, 625, 300))
        self.groupBox.setStyleSheet("background-color:rgba(4, 255, 4, 50);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.next_btn = QtWidgets.QPushButton(self.groupBox)
        self.next_btn.setGeometry(QtCore.QRect(220, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("QPushButton#next_btn{\n"
"background-color:rgb(102, 203, 0);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#next_btn: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.next_btn.setObjectName("next_btn")
        self.back_btn = QtWidgets.QPushButton(self.groupBox)
        self.back_btn.setGeometry(QtCore.QRect(20, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton#back_btn{\n"
"background-color:rgb(102, 203, 0);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#back_btn: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.back_btn.setObjectName("back_btn")
        self.main_btn = QtWidgets.QPushButton(self.groupBox)
        self.main_btn.setGeometry(QtCore.QRect(420, 225, 175, 40))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        self.main_btn.setFont(font)
        self.main_btn.setStyleSheet("QPushButton#main_btn{\n"
"background-color:rgb(102, 203, 0);\n"
"color: white;\n"
"font-family: Sura;\n"
"font-size: 15px;\n"
"border-radius : 7px;\n"
"\n"
"}\n"
"QPushButton#main_btn: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.main_btn.setObjectName("main_btn")
        self.Question_No = QtWidgets.QLineEdit(self.groupBox)
        self.Question_No.setGeometry(QtCore.QRect(60, 40, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Sura")
        font.setPointSize(1)
        font.setBold(False)
        font.setWeight(25)
        self.Question_No.setFont(font)
        self.Question_No.setStyleSheet("background-color:rgba(192, 192, 192,0);\n"
"\n"
"color: rgb(100, 79, 130);\n"
"font-size: 26px;\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:200;")
        self.Question_No.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Question_No.setPlaceholderText("")
        self.Question_No.setObjectName("Question_No")
        self.quote_area = QtWidgets.QLineEdit(self.groupBox)
        self.quote_area.setGeometry(QtCore.QRect(60, 100, 521, 31))
        self.quote_area.setStyleSheet("background-color:rgba(192, 192, 192,0);\n"
"\n"
"color: rgb(100, 79, 130);\n"
"font-size: 16px;\n"
"border-radius : 7px;\n"
"font-family:Sura;\n"
"font-weight:400;")
        self.quote_area.setReadOnly(True)
        self.quote_area.setObjectName("quote_area")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(410, 189, 171, 21))
        self.label_2.setStyleSheet("background-color:rgba(4, 255, 4, 20);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(416, 50, 191, 181))
        self.label.setStyleSheet("background-image:url(static/images/logo.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(820, 60, 175, 40))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.logout.setFont(font)
        self.logout.setStyleSheet("QPushButton#logout{\n"
"background-color:rgba(192, 192, 192,200);\n"
"color:rgb(124, 0, 186);\n"
"font-size: 12px;\n"
"border-radius : 7px;\n"
"\n"
"color: rgb(100, 79, 130);\n"
"\n"
"\n"
"}\n"
"QPushButton#logout: pressed {\n"
"background-color: rgb(117, 71, 255);\n"
"}")
        self.logout.setObjectName("logout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_btn.setText(_translate("Form", "Next"))
        self.back_btn.setText(_translate("Form", "Back"))
        self.main_btn.setText(_translate("Form", "Main Menu"))
        self.Question_No.setText(_translate("Form", "Inspiring Quotes"))
        self.quote_area.setText(_translate("Form", "The best prepartion for tommorow is doing your best today."))
        self.label_2.setText(_translate("Form", "H.Jackson Brwon.jr."))
        self.logout.setText(_translate("Form", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
